/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luiza
 */
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.FlowLayout;
import javax.swing.JOptionPane;
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblintro = new javax.swing.JLabel();
        btnPagarPix = new javax.swing.JButton();
        btnPagarDinheiro = new javax.swing.JButton();
        btnPagarCartao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblintro.setText("Escolha o método de pagamento:");

        btnPagarPix.setText("Pix");
        btnPagarPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarPixActionPerformed(evt);
            }
        });

        btnPagarDinheiro.setText("Dinheiro");
        btnPagarDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarDinheiroActionPerformed(evt);
            }
        });

        btnPagarCartao.setText("Cartão");
        btnPagarCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarCartaoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forma-de-pagamento.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/smartphone.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinheiro.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cartao-de-credito.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPagarPix)
                    .addComponent(lblintro)
                    .addComponent(btnPagarDinheiro)
                    .addComponent(btnPagarCartao))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblintro)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagarPix)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagarDinheiro)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagarCartao)
                    .addComponent(jLabel4))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarDinheiroActionPerformed
        abrirTelaValor("Dinheiro");
    }//GEN-LAST:event_btnPagarDinheiroActionPerformed

    private void btnPagarCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarCartaoActionPerformed
        abrirTelaValor("Cartão");
    }//GEN-LAST:event_btnPagarCartaoActionPerformed

    private void btnPagarPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarPixActionPerformed
        abrirTelaValor("PIX");
    }//GEN-LAST:event_btnPagarPixActionPerformed
    
    private void abrirTelaValor(String tipoPagamento) {
        // Cria nova janela para entrada do valor
        JFrame frameValor = new JFrame("Valor da Compra - " + tipoPagamento);
        frameValor.setSize(300, 150);
        frameValor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frameValor.setLayout(new FlowLayout());
        
        JLabel lblValor = new JLabel("Digite o valor da compra:");
        JTextField txtValor = new JTextField(10);
        JButton btnConfirmar = new JButton("Confirmar");
        
        btnConfirmar.addActionListener(e -> {
    String input = txtValor.getText().trim();
    
    // Verifica se o campo está vazio
    if (input.isEmpty()) {
        JOptionPane.showMessageDialog(frameValor, 
            "Por favor, digite um valor!",
            "Campo vazio", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    try {
        double valor = Double.parseDouble(input);
        
        // Validação para números negativos e zero
        if (valor <= 0) {
            JOptionPane.showMessageDialog(frameValor, 
                "O valor deve ser maior que zero!",
                "Valor inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        processarPagamento(tipoPagamento, valor);
        frameValor.dispose();
        
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(frameValor, 
            "Valor inválido! Digite apenas números (ex: 50.99).",
            "Erro de formato", JOptionPane.ERROR_MESSAGE);
    }
});
        
        frameValor.add(lblValor);
        frameValor.add(txtValor);
        frameValor.add(btnConfirmar);
        frameValor.setLocationRelativeTo(this);
        frameValor.setVisible(true);
    }

    private void processarPagamento(String tipoPagamento, double valor) {
        Pagamento pagamento;
        
        switch(tipoPagamento) {
            case "Dinheiro":
                pagamento = new Dinheiro(valor);
                break;
            case "Cartão":
                pagamento = new Cartao(valor);
                break;
            case "PIX":
                pagamento = new Pix(valor);
                break;
            default:
                throw new IllegalArgumentException("Tipo de pagamento inválido");
        }
        
        // Mostra o valor final e o recibo
        String mensagem = "Valor final: R$" + String.format("%.2f", pagamento.calcularTotal());
        JOptionPane.showMessageDialog(this, mensagem, "Valor Final", JOptionPane.INFORMATION_MESSAGE);
        pagamento.imprimirRecibo();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagarCartao;
    private javax.swing.JButton btnPagarDinheiro;
    private javax.swing.JButton btnPagarPix;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblintro;
    // End of variables declaration//GEN-END:variables
}
