/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luiza
 */
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class View extends javax.swing.JFrame {

    public View() {
        initComponents();
        setLocationRelativeTo(null); // Centraliza a janela
    }

    // Método para criar campos de entrada
    private Object[] createInputFields(String... labels) {
        Object[] components = new Object[labels.length * 2];
        for (int i = 0; i < labels.length; i++) {
            components[i*2] = labels[i];
            components[i*2+1] = new JTextField();
        }
        return components;
    }

    // Método para validar entrada numérica
    private double getValidatedDouble(JTextField field, String fieldName) {
        try {
            return Double.parseDouble(field.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Valor inválido para " + fieldName + ". Digite um número válido.",
                "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
            throw e;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblFormas = new javax.swing.JLabel();
        lblQuad = new javax.swing.JLabel();
        lblTriangulo = new javax.swing.JLabel();
        lblCirculo = new javax.swing.JLabel();
        lblCubo = new javax.swing.JLabel();
        lblPiramide = new javax.swing.JLabel();
        lblEsfera = new javax.swing.JLabel();
        btnQuadrado = new javax.swing.JButton();
        btnTriangulo = new javax.swing.JButton();
        btnCirculo = new javax.swing.JButton();
        btnCubo = new javax.swing.JButton();
        btnPiramide = new javax.swing.JButton();
        btnEsfera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Você pode calcular a área e o volume das formas geométricas abaixo:");

        lblFormas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cubes.png"))); // NOI18N

        lblQuad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/square.png"))); // NOI18N

        lblTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/triangle.png"))); // NOI18N

        lblCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circle.png"))); // NOI18N

        lblCubo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cube.png"))); // NOI18N

        lblPiramide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/prism.png"))); // NOI18N

        lblEsfera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sphere.png"))); // NOI18N

        btnQuadrado.setText("Quadrado");
        btnQuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuadradoActionPerformed(evt);
            }
        });

        btnTriangulo.setText("Triângulo");
        btnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrianguloActionPerformed(evt);
            }
        });

        btnCirculo.setText("Círculo");
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });

        btnCubo.setText("Cubo");
        btnCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuboActionPerformed(evt);
            }
        });

        btnPiramide.setText("Pirâmide");
        btnPiramide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiramideActionPerformed(evt);
            }
        });

        btnEsfera.setText("Esfera");
        btnEsfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsferaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEsfera)
                    .addComponent(lblPiramide)
                    .addComponent(lblCubo)
                    .addComponent(lblCirculo)
                    .addComponent(lblTriangulo)
                    .addComponent(lblQuad)
                    .addComponent(lblFormas))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnQuadrado)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCirculo)
                                .addComponent(btnTriangulo)
                                .addComponent(btnCubo)
                                .addComponent(btnPiramide)
                                .addComponent(btnEsfera)))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFormas))
                                .addGap(46, 46, 46)
                                .addComponent(lblQuad))
                            .addComponent(btnQuadrado))
                        .addGap(28, 28, 28)
                        .addComponent(lblTriangulo))
                    .addComponent(btnTriangulo))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCirculo)
                    .addComponent(btnCirculo))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCubo)
                    .addComponent(btnCubo))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPiramide)
                    .addComponent(btnPiramide))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEsfera)
                    .addComponent(btnEsfera))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuboActionPerformed
        // Abre diálogo para inserir a aresta
        // Cria um cubo com o valor informado
        // Exibe a área superficial e volume calculados
        Object[] fields = createInputFields("Aresta:");
        int option = JOptionPane.showConfirmDialog(this, fields, "Calcular Cubo", JOptionPane.OK_CANCEL_OPTION);
        
        if (option == JOptionPane.OK_OPTION) {
            try {
                double aresta = getValidatedDouble((JTextField)fields[1], "aresta");
                Cubo cubo = new Cubo(aresta);
                
                String resultado = String.format("Cubo:\nÁrea: %.2f\nVolume: %.2f", 
                    cubo.obterArea(), cubo.obterVolume());
                JOptionPane.showMessageDialog(this, resultado, "Resultado", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException ignored) {}
        }
    }//GEN-LAST:event_btnCuboActionPerformed

    private void btnEsferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsferaActionPerformed
        // Abre diálogo para inserir o raio
        // Cria uma esfera com o valor informado
        // Exibe a área superficial e volume calculados
        Object[] fields = createInputFields("Raio:");
        int option = JOptionPane.showConfirmDialog(this, fields, "Calcular Esfera", JOptionPane.OK_CANCEL_OPTION);
        
        if (option == JOptionPane.OK_OPTION) {
            try {
                double raio = getValidatedDouble((JTextField)fields[1], "raio");
                Esfera esfera = new Esfera(raio);
                
                String resultado = String.format("Esfera:\nÁrea: %.2f\nVolume: %.2f", 
                    esfera.obterArea(), esfera.obterVolume());
                JOptionPane.showMessageDialog(this, resultado, "Resultado", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException ignored) {}
        }
    }//GEN-LAST:event_btnEsferaActionPerformed

    private void btnQuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuadradoActionPerformed
        // Abre diálogo para inserir o lado
        // Cria um quadrado com o valor informado
        // Exibe a área calculada
        Object[] fields = createInputFields("Lado:");
        int option = javax.swing.JOptionPane.showConfirmDialog(
            this, fields, "Quadrado", javax.swing.JOptionPane.OK_CANCEL_OPTION);
            
        if (option == javax.swing.JOptionPane.OK_OPTION) {
            try {
                double lado = getValidatedDouble((javax.swing.JTextField)fields[1], "lado");
                Quadrado quadrado = new Quadrado(lado);
                String msg = String.format("Área: %.2f", quadrado.obterArea());
                javax.swing.JOptionPane.showMessageDialog(this, msg);
            } catch (NumberFormatException e) {
                // Usuário cancelou ou entrada inválida
            }
        }
    }//GEN-LAST:event_btnQuadradoActionPerformed

    private void btnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloActionPerformed
        // Abre diálogo para inserir base e altura
        // Cria um triângulo com os valores informados
        // Exibe a área calculada
        Object[] fields = createInputFields("Base:", "Altura:");
        int option = JOptionPane.showConfirmDialog(this, fields, "Calcular Área do Triângulo", JOptionPane.OK_CANCEL_OPTION);
        
        if (option == JOptionPane.OK_OPTION) {
            try {
                double base = getValidatedDouble((JTextField)fields[1], "base");
                double altura = getValidatedDouble((JTextField)fields[3], "altura");
                Triangulo triangulo = new Triangulo(base, altura);
                
                String resultado = String.format("Triângulo:\nÁrea: %.2f", triangulo.obterArea());
                JOptionPane.showMessageDialog(this, resultado, "Resultado", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException ignored) {}
        }
    }//GEN-LAST:event_btnTrianguloActionPerformed

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
        // Abre diálogo para inserir o raio
        // Cria um círculo com o valor informado
        // Exibe a área calculada
        Object[] fields = createInputFields("Raio:");
        int option = JOptionPane.showConfirmDialog(this, fields, "Calcular Área do Círculo", JOptionPane.OK_CANCEL_OPTION);
        
        if (option == JOptionPane.OK_OPTION) {
            try {
                double raio = getValidatedDouble((JTextField)fields[1], "raio");
                Circulo circulo = new Circulo(raio);
                
                String resultado = String.format("Círculo:\nÁrea: %.2f", circulo.obterArea());
                JOptionPane.showMessageDialog(this, resultado, "Resultado", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException ignored) {}
        }
    }//GEN-LAST:event_btnCirculoActionPerformed

    private void btnPiramideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiramideActionPerformed
        // Abre diálogo para inserir lado da base, altura e altura triangular
        // Cria uma pirâmide com os valores informados
        // Exibe a área superficial e volume calculados
        Object[] fields = createInputFields("Lado da base:", "Altura:", "Altura triangular lateral:");
        int option = JOptionPane.showConfirmDialog(this, fields, "Calcular Pirâmide", JOptionPane.OK_CANCEL_OPTION);
        
        if (option == JOptionPane.OK_OPTION) {
            try {
                double base = getValidatedDouble((JTextField)fields[1], "lado da base");
                double altura = getValidatedDouble((JTextField)fields[3], "altura");
                double alturaTriangulo = getValidatedDouble((JTextField)fields[5], "altura triangular");
                Piramide piramide = new Piramide(base, altura, alturaTriangulo);
                
                String resultado = String.format("Pirâmide:\nÁrea: %.2f\nVolume: %.2f", 
                    piramide.obterArea(), piramide.obterVolume());
                JOptionPane.showMessageDialog(this, resultado, "Resultado", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException ignored) {}
        }
    }//GEN-LAST:event_btnPiramideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnCubo;
    private javax.swing.JButton btnEsfera;
    private javax.swing.JButton btnPiramide;
    private javax.swing.JButton btnQuadrado;
    private javax.swing.JButton btnTriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCirculo;
    private javax.swing.JLabel lblCubo;
    private javax.swing.JLabel lblEsfera;
    private javax.swing.JLabel lblFormas;
    private javax.swing.JLabel lblPiramide;
    private javax.swing.JLabel lblQuad;
    private javax.swing.JLabel lblTriangulo;
    // End of variables declaration//GEN-END:variables
}
