/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade10;

/**
 *
 * @author luiza
 */
import javax.swing.*;
import java.awt.*;
import java.net.InetAddress;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class View extends javax.swing.JFrame {
    // Listas para armazenamento dos objetos
    private List<PerfilUsuario> perfis = new ArrayList<>();
    private List<Usuario> usuarios = new ArrayList<>();
    private List<Sessao> sessoes = new ArrayList<>();
    private List<LogAuditoria> logs = new ArrayList<>();
    
    // Contadores para gerar IDs sequenciais de 5 dígitos (10000-99999)
    private int nextPerfilId = 10000;
    private int nextUsuarioId = 10000;
    private int nextSessaoId = 10000;
    private int nextAuditoriaId = 10000;

    public View() {
        initComponents();
    }

    // Exibe janela de confirmação com os dados criados
    private void mostrarConfirmacao(String titulo, String mensagem) {
        JPanel panel = new JPanel(new BorderLayout(10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        JLabel iconLabel = new JLabel(new ImageIcon("success.png"));
        JTextArea textArea = new JTextArea(mensagem);
        textArea.setEditable(false);
        textArea.setBackground(panel.getBackground());
        textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        
        panel.add(iconLabel, BorderLayout.WEST);
        panel.add(new JScrollPane(textArea), BorderLayout.CENTER);
        
        JOptionPane.showMessageDialog(this, panel, titulo, JOptionPane.INFORMATION_MESSAGE);
    }
    
    // Método para obter o IP local
    private String obterIpLocal() {
        try {
            return InetAddress.getLocalHost().getHostAddress();
        } catch (Exception e) {
            return "127.0.0.1"; // Fallback para localhost
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCriarPerfil = new javax.swing.JButton();
        btnCriarUsuario = new javax.swing.JButton();
        btnCriarSessao = new javax.swing.JButton();
        btnCriarAuditoria = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade10/images/barra-de-menu.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Menu de Operações:");

        btnCriarPerfil.setText("Criar Perfil");
        btnCriarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarPerfilActionPerformed(evt);
            }
        });

        btnCriarUsuario.setText("Criar Usuário");
        btnCriarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarUsuarioActionPerformed(evt);
            }
        });

        btnCriarSessao.setText("Criar Sessão");
        btnCriarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarSessaoActionPerformed(evt);
            }
        });

        btnCriarAuditoria.setText("Criar Auditoria");
        btnCriarAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarAuditoriaActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade10/images/perfil.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade10/images/user.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade10/images/sessao.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade10/images/audit.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCriarAuditoria)
                    .addComponent(btnCriarSessao)
                    .addComponent(btnCriarPerfil)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCriarUsuario))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarPerfil)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarUsuario)
                    .addComponent(jLabel4))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarSessao)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarAuditoria)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarPerfilActionPerformed
        // Criação de perfil de usuário
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        
        JTextField descricaoField = new JTextField(20);
        JTextField permissoesField = new JTextField(20);
        
        panel.add(new JLabel("Descrição:"));
        panel.add(descricaoField);
        panel.add(new JLabel("Permissões (separadas por vírgula):"));
        panel.add(permissoesField);
        
        int result = JOptionPane.showConfirmDialog(
            null, panel, "Criar Novo Perfil", 
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        if (result == JOptionPane.OK_OPTION) {
            Long id = (long) nextPerfilId++;
            String descricao = descricaoField.getText();
            PerfilUsuario perfil = new PerfilUsuario(id, descricao);
            
            // Adiciona permissões
            String[] permissoes = permissoesField.getText().split(",");
            for (String permissao : permissoes) {
                perfil.adicionarPermissao(permissao.trim());
            }
            
            perfis.add(perfil);
            mostrarConfirmacao("Perfil criado com sucesso!", 
                "ID: " + id + "\nDescrição: " + descricao + "\nPermissões: " + perfil.getPermissoes());
        }
    }//GEN-LAST:event_btnCriarPerfilActionPerformed

    private void btnCriarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarUsuarioActionPerformed
        // Criação de usuário
        if (perfis.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Crie perfis antes de criar usuários!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        
        JTextField nomeField = new JTextField(20);
        JTextField emailField = new JTextField(20);
        JPasswordField senhaField = new JPasswordField(20);
        
        JComboBox<PerfilUsuario> perfilCombo = new JComboBox<>();
        for (PerfilUsuario perfil : perfis) {
            perfilCombo.addItem(perfil);
        }
        
        panel.add(new JLabel("Nome de Usuário:"));
        panel.add(nomeField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);
        panel.add(new JLabel("Senha:"));
        panel.add(senhaField);
        panel.add(new JLabel("Perfil:"));
        panel.add(perfilCombo);
        
        int result = JOptionPane.showConfirmDialog(
            null, panel, "Criar Novo Usuário", 
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        if (result == JOptionPane.OK_OPTION) {
            Long id = (long) nextUsuarioId++;
            String nome = nomeField.getText();
            String email = emailField.getText();
            String senha = new String(senhaField.getPassword());
            PerfilUsuario perfil = (PerfilUsuario) perfilCombo.getSelectedItem();
            
            Usuario usuario = new Usuario(id, nome, email, senha, perfil);
            usuarios.add(usuario);
            
            mostrarConfirmacao("Usuário criado com sucesso!", 
                "ID: " + id + "\nNome: " + nome + "\nEmail: " + email + "\nPerfil: " + perfil.getDescricao());
        }
    }//GEN-LAST:event_btnCriarUsuarioActionPerformed

    private void btnCriarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarSessaoActionPerformed
        // Criação de sessão
        if (usuarios.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Crie usuários antes de criar sessões!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        
        JComboBox<Usuario> usuarioCombo = new JComboBox<>();
        for (Usuario usuario : usuarios) {
            usuarioCombo.addItem(usuario);
        }
        
        panel.add(new JLabel("Usuário:"));
        panel.add(usuarioCombo);
        
        int result = JOptionPane.showConfirmDialog(
            null, panel, "Criar Nova Sessão", 
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        if (result == JOptionPane.OK_OPTION) {
            Long id = (long) nextSessaoId++;
            Usuario usuario = (Usuario) usuarioCombo.getSelectedItem();
            
            Sessao sessao = usuario.criarSessao();
            sessao.setId(id);
            sessoes.add(sessao);
            
            mostrarConfirmacao("Sessão criada com sucesso!", 
                "ID: " + id + "\nUsuário: " + usuario.getNomeUsuario() + 
                "\nToken: " + sessao.getToken());
        }
    }//GEN-LAST:event_btnCriarSessaoActionPerformed

    private void btnCriarAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarAuditoriaActionPerformed
        // Criação de log de auditoria
        if (usuarios.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Crie usuários antes de criar logs de auditoria!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        
        JTextField acaoField = new JTextField(20);
        
        JComboBox<Usuario> usuarioCombo = new JComboBox<>();
        for (Usuario usuario : usuarios) {
            usuarioCombo.addItem(usuario);
        }
        
        panel.add(new JLabel("Usuário:"));
        panel.add(usuarioCombo);
        panel.add(new JLabel("Ação:"));
        panel.add(acaoField);
        
        int result = JOptionPane.showConfirmDialog(
            null, panel, "Criar Log de Auditoria", 
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        if (result == JOptionPane.OK_OPTION) {
            Long id = (long) nextAuditoriaId++;
            Usuario usuario = (Usuario) usuarioCombo.getSelectedItem();
            String acao = acaoField.getText();
            String ip = obterIpLocal(); // IP obtido automaticamente
            
            LogAuditoria log = new LogAuditoria(id, usuario, acao, LocalDateTime.now(), ip);
            logs.add(log);
            
            mostrarConfirmacao("Log de auditoria criado com sucesso!", 
                "ID: " + id + "\nUsuário: " + usuario.getNomeUsuario() + 
                "\nAção: " + acao + "\nIP: " + ip + "\nData/Hora: " + log.getDataHora());
        }
    }//GEN-LAST:event_btnCriarAuditoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarAuditoria;
    private javax.swing.JButton btnCriarPerfil;
    private javax.swing.JButton btnCriarSessao;
    private javax.swing.JButton btnCriarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
